export * from './Arbitrary'
export * as Associative from './Associative'
export * as AssociativeBoth from './AssociativeBoth'
export * as AssociativeFlatten from './AssociativeFlatten'
export * as Commutative from './Commutative'
export * as Contravariant from './Contravariant'
export * as Covariant from './Covariant'
export * as Eq from './Eq'
export * as Identity from './Identity'
export * as IdentityBoth from './IdentityBoth'
export * as IdentityFlatten from './IdentityFlatten'
export * as Inverse from './Inverse'
export * as Ord from './Ord'
