export * from './Arbitrary.js'
export * as Associative from './Associative.js'
export * as AssociativeBoth from './AssociativeBoth.js'
export * as AssociativeFlatten from './AssociativeFlatten.js'
export * as Commutative from './Commutative.js'
export * as Contravariant from './Contravariant.js'
export * as Covariant from './Covariant.js'
export * as Eq from './Eq.js'
export * as Identity from './Identity.js'
export * as IdentityBoth from './IdentityBoth.js'
export * as IdentityFlatten from './IdentityFlatten.js'
export * as Inverse from './Inverse.js'
export * as Ord from './Ord.js'
